import 'package:get/get.dart';

class AppStrings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en": {
          "Let's Explore the Italy": "Let's Explore the Italy",
          "Let’s explore the Italy with us with just a few clicks":
              "Let’s explore the Italy with us with just a few clicks",
          "Visit tourist attractions": "Visit tourist attractions",
          "Find thousands of tourist destinations ready for you to visit":
              "Find thousands of tourist destinations ready for you to visit",
          "Get ready for next trip": "Get ready for next trip",
          "Next": "Next",
          "Get Started": "Get Started",
          "Welcome": "Welcome",
          "Hi": "Hi",
          "Search place, tour, etc.": "Search place, tour, etc.",
          "from": "from",
          "night": "night",
          "Tours & Tickets": "Tours & Tickets",
          "Stays": "Stays",
          "Travel Blog": "Travel Blog",
          "Special Offers": "Special Offers",
          "Explore Now": "Explore Now",
          "My Gallery": "My Gallery",
          "Notification": "Notification",
          "Language": "Language",
          "Settings": "Settings",
          "Privacy": "Privacy",
          "Help": "Help",
          "About Us": "About Us",
          "Logout": "Logout",
          "Get Now": "Get Now",
          "Discount": "Discount",
          "Reviews": "Reviews",
          "Notifications": "Notifications",
          "About this activity": "About this activity",
          "Free cancellation": "Free cancellation",
          "Cancel up to 24 hours in advance to receive a full refund":
              "Cancel up to 24 hours in advance to receive a full refund",
          "Duration 3 hours": "Duration 3 hours",
          "Check availability to see starting times":
              "Check availability to see starting times",
          "Group of 15 people max.": "Group of 15 people max.",
          "From:": "From:",
          "person": "person",
          "Book Now": "Book Now",
          "The Original Experience": "The Original Experience",
          "What’s included": "What’s included",
          "Full description": "Full description",
          "Highlights": "Highlights",
          "Prepare for the activity": "Prepare for the activity",
          "Know before you go": "Know before you go",
          "Meeting point": "Meeting point",
          "Copy address": "Copy address",
          "Customer reviews": "Customer reviews",
          "reviews from verified customers": "reviews from verified customers",
          "See all reviews": "See all reviews",
          "You might also like": "You might also like",
          "Location": "Location",
          "Guest reviews": "Guest reviews",
          "Guests": "Guests",
          "Great Location": "Great Location",
          "95% of recent guests gave the location a 5-star rating":
              "95% of recent guests gave the location a 5-star rating",
          "Description": "Description",
          "Read More": "Read More",
          "Facilities": "Facilities",
          "About this accommodation": "About this accommodation",

          "Bookings": "Bookings",
          "Booking Summary": "Booking Summary",

          "Wifi": "Wifi",
          "Air Conditioner": "Air Conditioner",
          "TV": "TV",
          "Private parking": "Private parking",

          "Show All": "Show All",
          "Show Less": "Show Less",

          "Check in": "Check in",

          "Map of": "Map of",
          "FAQs": "FAQs",
          "Comments": "Comments",
          "Trips": "Trips",
          "Favourites": "Favourites",
          "Photos": "Photos",
          "Reserve": "Reserve",

          "Please enter your": "Please enter your",
          "Please enter a valid Email": "Please enter a valid Email",
          "Something went wrong": "Something went wrong",
          "This email is already registered with another account.":
              "This email is already registered with another account.",

          //--------strings2
          "Email": "Email",
          "Password": "Password",
          "Remember me": "Remember me",
          "Forgot password?": "Forgot password?",
          "Create Account": "Create Account",
          "Sign in": "Sign in",
          "Input your Email": "Input your Email",
          "Forgot your password": "Forgot your password",
          "Submit": "Submit",
          "Create New Password": "Create New Password",
          "Your password must include at least one symbol and be 8 or more characters long.":
              "Your password must include at least one symbol and be 8 or more characters long.",
          "Save": "Save",
          "Create your Account": "Create your Account",
          "What's is Your name": "What's is Your name",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Input Email": "Input Email",
          "What's is Your Email": "What's is Your Email",
          "Create Password": "Create Password",
          "Create a Password": "Create a Password",
          "Verification": "Verification",
          "I'd like to received marketing and policy communication from Rome Italy Travel and its partners.":
              "I'd like to received marketing and policy communication from Rome Italy Travel and its partners.",

          "New Picture": "New Picture",
          "Update Your Profile": "Update Your Profile",
          "PROFILE SETTING": "PROFILE SETTING",
          "FAVOURITE": "FAVOURITE",
          "Recently Saved": "Recently Saved",
          "Tours": "Tours",
          "Activities": "Activities",
          "Restaurants": "Restaurants",
          "Blog": "Blog",
          "About this event": "About this event",
          "About this deal": "About this deal",
          "About the": "About the",
          "Push Notification": "Push Notification",
          "Review Screen": "Review Screen",
          "Payment Completed": "Payment Completed",
          "Nights to stay": "Nights to stay",
          "Price Per Night": "Price Per Night",
          "Total Price": "Total Price",
          "Tour Title": "Tour Title",
          "Tour Date": "Tour Date",
          "Number of participants": "Number of participants",
          "Price per person": "Price per person",
          "Search Results": "Search Results",
          "No Data Found": "No Data Found",
          "My Trip History": "My Trip History",
          "Image updated successfully": "Image updated successfully",
          "Discover Rome’s Best Bars on our Tipsy Tour":
              "Discover Rome’s Best Bars on our Tipsy Tour",
          "Visiting Rome for the first time? Join us on our famous Tipsy Tour of Rome!":
              "Visiting Rome for the first time? Join us on our famous Tipsy Tour of Rome!",
          "Share your Review with us": "Share your Review with us",
          "Get flat": "Get flat",
          "Tipsy Tour info": "Tipsy Tour info",
          "Tipsy Tour": "Tipsy Tour",
          "Booking Details": "Booking Details",
          "Edit Booking": "Edit Booking",
          "Preferred Drink at Location 1": "Preferred Drink at Location 1",
          "Please Select Drink": "Please Select Drink",
          "Please Fill all participants details":
              "Please Fill all participants details",
          "Payment Successfully": "Payment Successfully",
          "Cancelled ": "Cancelled ",
          "Create account": "Create account",
          "Check In Date": "Check In Date",
          "Number of days": "Number of days",
          "Book now": "Book now",
          "Please Select Check In date": "Please Select Check In date",
          "Enter Number of Participants": "Enter Number of Participants",
          "Adult": "Adult",
          "Child": "Child",
          "Choose a Date": "Choose a Date",
          "Choose a Time": "Choose a Time",
          "Continue": "Continue",
          "Please select Time": "Please select Time",
          "Tour Booking Details": "Tour Booking Details",
          "Booked Slot": "Booked Slot",
          "Price per Person": "Price per Person",
          "Participants Details": "Participants Details",
          "Preferred Drink": "Preferred Drink",
          ////
          "Optional": "Optional",
          "Not Available": "Not Available",
          "Please note: ": "Please note: ",
          "After your purchase is confirmed we will email you a confirmation.":
              "After your purchase is confirmed we will email you a confirmation.",
          "The Selected Date is not available":
              "The Selected Date is not available",
          "Offer Title": "Offer Title",
        }
      };
}
